export class M2000Alarms {

    constructor(
        public id?: string,
        public logSerialNumber?: string,
        public objectIdentityName?: string,
        public objectIdentity?: string,
        public productName?: string,
        public NEType?: string,
        public NEObjectIdentity?: string,
        public alarmSource?: string,
        public equipementAlarmSerialNumber?: string,
        public alarmName?: string,
        public type?: string,
        public severity?: string,
        public status?: string,
        public occurrenceTime?: Date,
        public acknowledgementTime?: Date,
        public clearanceTime?: Date,
        public acknowledgementOperator?: string,
        public clearanceOperator?: string,
        public locationInformation?: string,
        public linkFDN?: string,
        public linkName?: string,
        public linkType?: string,
        public alarmIdentifier?: string,
        public alarmID?: string,
        public objectInstanceType?: string,
        public autoClear?: string,
        public alarmClearType?: string,
        public businessAffected?: string,
        public additionalText?: string,
        public arrivedUtcTime?: string,
        public listId?: string,
        public relatedLogId?: string,
        public agentID?: string,
        public rootID?: string,
        public showFlag?: string,
        public techno?: string,
        public CI?: string,
        public site?: string,
        public active?: boolean,
        public VRI?: number,
        public AlarmeCauseNURId?: string,
        public localCauseInfo ?: any,
        public localExclusion?: boolean,
        public DELTA?: number,
        public DELTAREEL?: number,
        public NRJInfo?: any
        ){

    }
}