export class NETACTALARM {

    constructor(
        public id: string,
        public notificationId?: string,
        public alarmNumber?: string,
        public alarmType?: string,
        public severity?: string,
        public alarmTime?: Date,
        public probableCause?: string,
        public probableCauseCode?: string,
        public alarmText?: string,
        public distinguishedName?: string,
        public objectClass?: string,
        public acknowledgementState?: string,
        public acknowledgementTimeUN?: Date,
        public acknowledgementUser?: string,
        public cancelState?: string,
        public cancelTime?: Date,
        public cancelUser?: string,
        public name?: string,
        public maintenanceRegionName?: string,
        public siteName?: string,
        public sitePriority?: string,
        public siteAddress?: string,
        public extraInformation?: string,
        public diagnosticInfo?: string,
        public userAdditionalInformation?: string,
        public supplementaryInformation?: string,
        public additionalInformation1?: string,
        public additionalInformation2?: string,
        public additionalInformation3?: string,
        public correlationIndicator?: string,
        public notesIndicator?: string,
        public troubleTicketIndicator?: string,
        public alarmSound?: string,
        public instanceCounter?: string,
        public consecutiveNumber?: string,
        public alarmInsertionTime?: Date,
        public alarmUpdateTime?: Date,
        public techno?: string,
        public CI?: string,
        public site?: string,
        public active?: boolean,
        public VRI?: number,
        public AlarmeCauseNURId?: string,
        public localCauseInfo ?: any,
        public localExclusion?: boolean,
        public DELTA?: number,
        public DELTAREEL?: number,
        public NRJInfo?: any
        ){

    }
}